# .github/workflows/release.yml
name: Build & Publish

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - run: pip install --upgrade build
      - run: python -m build
      - uses: softprops/action-gh-release@v2
        with:
          files: dist/*.whl
